### ISSUE TITLE
GUI版的可移植性

### ISSUE THREAD

**Issue by 2018wzh** [ljlVink/WJX-Fastanswer#2]
建议UI换成Qt，这样可以跨平台开发，最好再加上说明文档

**Comment by ljlVink** [comment]
因为V1--V5程序改动太大，说明都删了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WwZzHh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月4日(星期一) 下午4:53
收件人:&nbsp;"ljlVink/WJX-Fastanswer"<WJX-Fastanswer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ljlVink/WJX-Fastanswer] GUI版的可移植性 (#2)





 
建议UI换成Qt，这样可以跨平台开发，最好再加上说明文档
